drop database BMS_DB1;
create database BMS_DB1;


use BMS_DB1;

-- CUSTOMER_PERSONAL_INFO

CREATE TABLE CUSTOMER_PERSONAL_INFO
( 
 CUSTOMER_ID VARCHAR(5),
 CUSTOMER_NAME VARCHAR(30),
 DATE_OF_BIRTH DATE,
 GUARDIAN_NAME VARCHAR(30),
 ADDRESS VARCHAR(50),
 CONTACT_NO BIGINT(10),
 MAIL_ID VARCHAR(30),
 GENDER VARCHAR(30),
 MARITIAL_STATUS VARCHAR(30),
 IDENTIFICATION_DOC_TYPE VARCHAR(20),
 ID_DOC_NO VARCHAR(20),
 CITIZENSHIP VARCHAR(10),
 CONSTRAINT CUST_PERRS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);


-- CUSTOMER REFERENCE INFO 

CREATE  TABLE CUSTOMER_REFERENCE_INFO
	(
	CUSTOMER_ID VARCHAR(5),
    REFERENCE_ACC_NAME VARCHAR(20),
    REFERENCE_ACC_NO BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(50),
    RELATION VARCHAR(25),
    CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);
-- BANK INFO
CREATE TABLE BANK_INFO
(
	IFSC_CODE VARCHAR(15),
    BANK_NAME VARCHAR(25),
    BRANCH_NAME VARCHAR(25),
    CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
    
);

-- ACCOUNT INFO

CREATE TABLE ACCOUNT_INFO
(
	ACCOUNT_NO BIGINT(16),
    CUSTOMER_ID VARCHAR(5),
    ACCOUNT_TYPE VARCHAR(10),
    ACTIVATION_DATE DATE,
    IFSC_CODE VARCHAR(10),
    INTEREST DECIMAL(7,2),
    INITIAL_DEPOSIT BIGINT(10),
    CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
    CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
    CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
    );
    
    -- COMMAND USED TO GET THE INFO REGARDING THE CREATED TABLES
    SHOW TABLES;
    -- INSERT DATA INTO BANK_INFO TABLE
    INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HDFC001','HDFC BANK','MANJALPUR BRANCH');
    INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HDFC002','HDFC BANK','KALALI BRANCH');
    INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBIL001','SBI','MANJALPUR BRANCH');
    INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBIL002','SBI','AKOTA BRANCH');
    INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('KOTK001','KOTAK BANK','MANJALPUR BRANCH');
    INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('RBLL001','RBL BANK','KALUPURA BRANCH');
    
    SELECT* FROM BANK_INFO;
    
    -- INSERT DATA INTO CUSTOMER_PERSONAL_INFO
    
    INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITIAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES (00001,'Harsh','2005-04-17','Girish Patil','5 Park Royal',1234567890,'abc@gmail.com','Male','Unmarried','Aadhar Card','abc123','Indian');
    INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITIAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES (00002,'Ayush','2003-10-12','Harry','5 Dhaval Park',1234567897,'bac@gmail.com','Male','Unmarried','Aadhar Card','bac123','Indian');
    INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITIAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES (00003,'Divyansh','2004-03-3','Yatharth','5 Suncity Paradise',1234567899,'cba@gmail.com','Male','Unmarried','Aadhar Card','cba123','Indian');
   
   -- INSERT DATA INTO CUSTOMER_REFERENCE_INFO
    
    INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION) VALUES('00002','HARSH','123456','12 SHREEJIDHAM','FRIEND');
    INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION) VALUES('00003','AYUSH','123455','13 SHREEJIDHAM','FRIEND');
    INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION) VALUES('00001','DIVYANSH','123454','14 SHREEJIDHAM','FRIEND');


	-- INSERT DATA IN ACCOUNT INFO
    
    INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,cUSTOMER_ID,ACCOUNT_TYPE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES(1234567,00001,'SAVINGS','2020-04-17','HDFC001',750,50000);
    INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,cUSTOMER_ID,ACCOUNT_TYPE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES(1234565,00002,'SAVINGS','2020-04-19','KOTK001',1200,12000);
    INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,cUSTOMER_ID,ACCOUNT_TYPE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES(1234566,00003,'CURRENT','2020-04-18','RBLL001',150,14295);
    
    SHOW DATABASES